stages:
  - test

##########
## Develop
##########
test to develop:
  stage: test
  image: python:3.6
  script:
    - pip install -e .[dev] -U tox
    - tox
  only:
    - /develop/
  environment: development
