stages:
  - test
  - deploy

##########
## Develop
##########
test to develop: &tox
  stage: test
  image: python:3.6
  script:
    - pip install -e .[dev] -U tox
    - tox
  only:
    - /develop/
  environment: development

##########
## Homolog
##########
test to homolog:
  << : *tox
  only:
    - /master/
  environment: homolog

deploy to homolog:
  stage: deploy
  image: python:3.6
  script:
    - python setup.py sdist
    - pip install twine
    - ls ./dist | while read pkg; do twine upload -u $TESTPIPY_USER -p $TESTPIPY_PASSWORD --repository testpypi ./dist/$pkg; done
  only:
    - /develop/
  environment: homolog
